### ISSUE TITLE
Expansion of features in the UI

### ISSUE THREAD

**Issue by gabriel-indik** [LF-Decentralized-Trust-labs/paladin#466]
### What would you like to be added?

Incorporate new features to the Paladin web based graphical user interface.

### Why is this needed?

Currently the UI allows the user to explore transactions, submissions and registry entries. This can be expanded to to a larger feature set.

### List of features

  - [x] State Query
  - [x] Key management browsing
  - [x] Simple key lookup https://github.com/LF-Decentralized-Trust-labs/paladin/issues/478
  - [x] ABI upload https://github.com/LF-Decentralized-Trust-labs/paladin/issues/468
  - [ ] Navigating the complex data inside of a transaction receipt
  - [x] Improve live update status and feedback https://github.com/LF-Decentralized-Trust-labs/paladin/issues/468

**Comment by gabriel-indik** [comment]
# Current state of the UI
There are three main panels

## Indexer

<img width="1336" alt="Screenshot 2024-12-05 at 10 17 30 AM" src="https://github.com/user-attachments/assets/e3f0ddbd-1a56-437c-a5fb-1449582fadd2">

<img width="1336" alt="Screenshot 2024-12-05 at 10 17 45 AM" src="https://github.com/user-attachments/assets/5c78bdcb-6cd1-47f2-b74c-5acbbd51080b">

## Submissions

<img width="1338" alt="Screenshot 2024-12-05 at 10 17 55 AM" src="https://github.com/user-attachments/assets/f4ac8953-eae7-496e-b888-4ed4f8260221">

<img width="1336" alt="Screenshot 2024-12-05 at 10 18 10 AM" src="https://github.com/user-attachments/assets/e254c5e8-093b-4424-b7ba-739fb09773ff">

## Registry

<img width="1337" alt="Screenshot 2024-12-05 at 10 18 26 AM" src="https://github.com/user-attachments/assets/894bd8a4-0649-40e6-b4a9-6250b52dea19">

<img width="1336" alt="Screenshot 2024-12-05 at 10 18 48 AM" src="https://github.com/user-attachments/assets/296344d8-b3d4-44ca-b49d-14e42b45ac5b">

**Comment by peterbroadhurst** [comment]
This list is great @gabriel-indik.
Trying to fill out some detail on the requirements I see under each items, so maybe they can be split out to separate issues and prioritized... I'm putting them in rough prioritization here:

### 1. Navigating the complex data inside of a transaction receipt

- [x] The experience for "picking" a sub-transaction in an `Atomic (4)` one needs to give you some insight into which are which _without_ picking one [#470](https://github.com/LF-Decentralized-Trust-labs/paladin/issues/470)
    - Is the whole `State Receipt` available yes/no?
    - The Domain
- [x] We need to show you the details of the _public_ transaction/events (there are APIs in Paladin for this)
    - For a transaction clicked on the left side
    - For an event clicked **on the right side** (currently this is just the event hex)


### 2 Simple key lookup

This folds under "network" (not keys) - you are asking for `some.key@some.node` here, so it's got to be clearly related to navigating the nodes.

### 3 ABI upload https://github.com/LF-Decentralized-Trust-labs/paladin/issues/468

- The ability to paste/file-drop an ABI in
- Deferrable: list of what ABIs have been uploaded
    - List of functions
    - List of events
    - List of errors
    - List of ABI-hashes (least useful)

### 4 Key management browsing

This is likely a whole new section of the experience that needs to be clear it's related to the **local** key management:
- [x] Navigation of keys in the `something.nested.here` path hierarchy
    - Direct lookup to a known fully qualified key
    - Nested navigation (like any folder/tree structure)
- [x] Reverse lookup of keys by verifier
    - With shortcut for Eth address
- Displaying key information
   - [x] The wallet a key is in
   - [x] The list of verifiers that have been resolved for a key
        - With some priority on the eth address

### 5. Transaction debug

If a transaction is pending, let you grab the debug information for it.
This might be just JSON right now.

> Added to the original list, as I think it fits here in the priority.

### 6. Network navigation https://github.com/LF-Decentralized-Trust-labs/paladin/pull/510

> Added to the original list, as I think it fits here in the priority.

- Reconciling the relationship between this and the "registry"
- Listing currently connected nodes
- Listing performed/queued state transfers to remote nodes

### 7. State Query

- Build a UX around our JSON Query syntax (re-usable in many places)
- Add a panel to use it to run queries against the state system

**Comment by gabriel-indik** [comment]
All of the items have been implemented, except for "Navigating the complex data inside of a transaction receipt". That items seems to require further conversations in order to get the design right before the implementation can begin. A separate issue has been opened to handle that: https://github.com/LF-Decentralized-Trust-labs/paladin/issues/470
